adjective1 = input("write an adjective(description): ")
noun1 = input("write a name,place or animal: ")
action = input("write a action word: ")
verb = input("write a verb in the past tense: ")
adjective2 = input("write an adjective: ")
print(f"today i went to a {adjective1} zoo")
print(f"there were many {noun1} in the zoo")
print(f"one of them challenged me to {action}")
print(f"i ignored it so it {verb} on me")
print(f"and i defeated the {noun1} and was {adjective2}")